### ISSUE TITLE
Set Up API File Structure

### ISSUE THREAD

**Issue by JenniferLipps** [nss-evening-cohort-9/FightAndFeast.api#1]
# User Story
As a Developer, I want to have an established file structure for the project API

# Acceptance Criteria
**When** I open the solution folder for FeastAndFight.api,
**Then** I should see the folders and files outlined in the Dev Notes

# Dev Notes

- Create a Models folder with the following classes:

Customer.cs
Seller.cs
Product.cs
ProductType.cs
Cart.cs
Order.cs
PaymentType.cs
EmergencyContact.cs
Club.cs
Insurance.cs
InsuranceType.cs

- Create a DataAccess folder with the following classes:

CustomerRepository.cs
SellerRepository.cs
ProductRepository.cs
ProductTypeRepository.cs
CartRepository.cs
OrderRepository.cs
PaymentTypeRepository.cs
EmergencyContactRepository.cs
ClubRepository.cs
InsuranceRepository.cs
InsuranceTypeRepository.cs

- Create a Controllers folder with the following classes:

CustomerController.cs
SellerController.cs
ProductController.cs
ProductTypeController.cs
CartController.cs
OrderController.cs
PaymentTypeController.cs
EmergencyContactController.cs
ClubController.cs
InsuranceController.cs
InsuranceTypesController.cs

- Create a Commands folder with the following classes:

AddCustomerCommand.cs
UpdateCustomerCommand.cs
AddSellerCommand.cs
UpdateSellerCommand.cs
AddProductCommand.cs
UpdateProductCommand.cs
AddProductTypeCommand.cs
UpdateProductTypeCommand.cs
AddCartCommand.cs
UpdateCartCommand.cs
AddOrderCommand.cs
UpdateOrderCommand.cs
AddPaymentTypeCommand.cs
UpdatePaymentTypeCommand.cs
AddEmergencyContactCommand.cs
UpdateEmergencyContactCommand.cs
AddClubCommand.cs
UpdateClubCommand.cs
AddInsuranceCommand.cs
UpdateInsuranceCommand.cs
AddInsuranceTypeCommand.cs
UpdateInsuranceTypeCommand.cs

**Comment by JenniferLipps** [comment]
# User Story
As a Developer, I want to have an established file structure for the project API

# Acceptance Criteria
**When** I open the solution folder for FeastAndFight.api,
**Then** I should see the folders and files outlined in the Dev Notes

# Dev Notes

- Create a Models folder with the following classes:

Customer.cs
Seller.cs
Product.cs
ProductType.cs
Cart.cs
Order.cs
PaymentType.cs
EmergencyContact.cs
Club.cs
Insurance.cs
InsuranceType.cs

- Create a DataAccess folder with the following classes:

CustomerRepository.cs
SellerRepository.cs
ProductRepository.cs
ProductTypeRepository.cs
CartRepository.cs
OrderRepository.cs
PaymentTypeRepository.cs
EmergencyContactRepository.cs
ClubRepository.cs
InsuranceRepository.cs
InsuranceTypeRepository.cs

- Create a Controllers folder with the following classes:

CustomersController.cs
SellersController.cs
ProductsController.cs
ProductTypesController.cs
CartsController.cs
OrdersController.cs
PaymentTypesController.cs
EmergencyContactsController.cs
ClubsController.cs
InsurancesController.cs
InsuranceTypesController.cs

- Create a Commands folder with the following classes:

AddCustomerCommand.cs
UpdateCustomerCommand.cs
AddSellerCommand.cs
UpdateSellerCommand.cs
AddProductCommand.cs
UpdateProductCommand.cs
AddProductTypeCommand.cs
UpdateProductTypeCommand.cs
AddCartCommand.cs
UpdateCartCommand.cs
AddOrderCommand.cs
UpdateOrderCommand.cs
AddPaymentTypeCommand.cs
UpdatePaymentTypeCommand.cs
AddEmergencyContactCommand.cs
UpdateEmergencyContactCommand.cs
AddClubCommand.cs
UpdateClubCommand.cs
AddInsuranceCommand.cs
UpdateInsuranceCommand.cs
AddInsuranceTypeCommand.cs
UpdateInsuranceTypeCommand.cs

**Comment by bobbybaxter** [comment]
Completed scaffolding and pushed up.  Additional Models, DataAccess, and Controllers were created to include the rest of the tables shown in the ERD.
