### ISSUE TITLE
create SQL DB and tables, and seed the database

### ISSUE THREAD

**Issue by Lwamtekie** [nss-evening-cohort-9/FightAndFeast.api#2]
User Story 
As a Developer I should see a Database that matches the provided ERD complete with seed data in the products table.

Development
Create Database FightAndFeast
create  Table in Sql
create all needed tables listed in ERD

**Comment by bobbybaxter** [comment]
Go to https://dbdiagram.io/d/5dd03fc1edf08a25543e01d0 for all of the ERD details.

![FightAndFeast](https://user-images.githubusercontent.com/5022594/69291907-3349df00-0bca-11ea-8fc2-0d3005cafce4.png)

**Comment by bobbybaxter** [comment]
SQL queries sent via Slack.
