### ISSUE TITLE
Customer can search for products

### ISSUE THREAD

**Issue by JenniferLipps** [nss-evening-cohort-9/FightAndFeast.api#67]
## User Story
As a User, when I navigate to the site, I should see a search bar at the top that searches through the products.

## AC
**Given** Clubs have items to purchase
**When** the User clicks on the search input field in the navbar
**And** the User types the name of the product
**When** pressing the enter key
**Then** products matching the keyword show in the page

## Dev Notes
- Add a search input bar to the center of the Navbar
- Look into using Fuse.js to implement a fuzzy search

**Comment by JenniferLipps** [comment]
***Given*** sellers have items to purchase

***When*** the user clicks on the search input field in the navigation bar

***And*** the user types the name of a product

***When*** pressed the enter key

***Then*** products matching the keyword show in the page

**Comment by bobbybaxter** [comment]
https://www.jondjones.com/frontend/react/components/how-to-build-a-filterable-search-bar-in-react
